### ISSUE TITLE
[Android Course] Project 2: Google Image Search

### ISSUE THREAD

**Issue by kristeaac** [kristeaac/codepath-project-2-google-image-search#1]
My app is complete, please review. /cc @codepathreview @codepath

I originally had image color and type as filter options which you can see in the commit history, but decided to take them out of the interface since these no longer seem to be supported in the Google Image Search API.

I'd also like to note that I had some trouble getting endless scroll to work with the StaggeredGridView. I'll probably try to tackle this again later, but wanted to get my submission in before the deadline.

Thanks for reviewing!

**Comment by codepathreview** [comment]
:+1: Great submission once again, Kristy! A few notes after checking out the code:

* Properly sent and received relevant filters using a bundle to pass data between activities
* Correctly named packages and organized source files
* Properly used spinners (with populated values) to allow users to select filters
* Great effort at polishing the UI
* Consider adding the [share intent](https://guides.codepath.com/android/Sharing-Content-with-Intents) to the image detail view!
* Consider using the [ViewHolder pattern](https://github.com/codepath/android_guides/wiki/Using-an-ArrayAdapter-with-ListView#improving-performance-with-the-viewholder-pattern) to improve performance of photos `ListView`.
* Consider using Parcelable instead of Serializable ([benefits](http://stackoverflow.com/a/5551155))
* Good job moving the search field into the [SearchView](http://guides.codepath.com/android/Extended-ActionBar-Guide#adding-searchview-to-actionbar)
* Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.

**Comment by kristeaac** [comment]
Thanks for the feedback!
